apiVersion: apps/v1
kind: Deployment
metadata:
  name: motorq-api
  labels:
    app: motorq-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: motorq-api
  template:
    metadata:
      labels:
        app: motorq-api
    spec:
      containers:
      - name: motorq-api
        image: motorq-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: motorq-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: motorq-api-service
spec:
  selector:
    app: motorq-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
